version: '3.7'

services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      - WEB_PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    networks:
      - web
  
networks:
  web:
    driver: bridge
